{{/*
MachineDeployment resource - Worker node deployment
This resource manages the lifecycle of worker nodes by:
- Defining the desired number of worker replicas
- Referencing the machine template for infrastructure provisioning
- Referencing the worker config template for k0s configuration
*/}}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.name" . }}
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: {{ .Values.workersNumber }}
  selector:
    matchLabels: {}
  template:
    spec:
      clusterName: {{ include "cluster.name" . }}
      version: {{ .Values.k0s.version }}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: {{ include "k0sworkerconfigtemplate.name" . }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ include "hcloudmachinetemplate.worker.name" . }}
